spring:
  application:
    name: apigateway

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

zuul:
  ribbon:
    eager-load:
      enabled: true # Enables eager loading of Ribbon clients on startup.
  routes:
    chaining-route:
      path: /chaining/**
      serviceId: service-a

management:
  endpoints:
    # enable or disable all endpoints by default.
    enabled-by-default: true
    web:
      exposure:
        include: hystrix.stream, info, health